apiVersion: 1
datasources:
  - name: Inventory
    uid: inventory
    type: grafana-postgresql-datasource
    url: postgres:5432
    user: grafana_ro
    isDefault: true
    jsonData:
      database: inventory
      sslmode: disable
      postgresVersion: 1600
    secureJsonData:
      password: ${GRAFANA_RO_PASSWORD}
